# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain_name', models.CharField(max_length=50)),
                ('father_domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.domain')),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('max_score', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('people_tried', models.IntegerField(default=0)),
                ('people_succeed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0, max_length=4)),
                ('task_text', models.TextField(max_length=15000)),
                ('father_domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.domain')),
                ('father_subdomain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.TextField(blank=True, max_length=15000)),
                ('test_output', models.TextField(max_length=15000)),
                ('father_task_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='TestsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=30)),
                ('subdomain', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=30)),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python3', models.IntegerField(default=0)),
                ('cpp', models.IntegerField(default=0)),
                ('c', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
