# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='path',
            field=models.TextField(max_length=15000),
        ),
    ]
