# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_auto_20161127_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.TextField(max_length=15000)),
                ('test_output', models.TextField(max_length=15000)),
                ('father_task_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task')),
            ],
        ),
    ]
