# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='father_task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_input',
            field=models.TextField(blank=True, max_length=15000),
        ),
    ]
