# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_auto_20161130_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='father_task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task'),
        ),
    ]
