# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_auto_20161130_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=30)),
                ('subdomain', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=30)),
                ('result', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='father_task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task'),
        ),
    ]
