# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_auto_20161201_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cppPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='father_task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pythonPoints',
            field=models.IntegerField(default=0),
        ),
    ]
