# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0010_auto_20161202_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cppPoints',
            new_name='cpp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pythonPoints',
            new_name='python3',
        ),
        migrations.AlterField(
            model_name='test',
            name='father_task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.task'),
        ),
    ]
